services:
  api:
    container_name: test_api
    environment: 
      - PGUSER=mongodontbother
      - PGHOST=db
      - PGPASSWORD=hush
      - PGDATABASE=habitTrack_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=habitTrack_test
      - POSTGRES_USER=mongodontbother
      - POSTGRES_PASSWORD=hush
volumes:
  test_db:
networks: 
  default:
    name: habitTrack_test




