services:
  api:
    container_name: dev_api
    ports:
      - 3000:3000
    environment:
      - PGUSER=mongodontbother
      - PGHOST=db
      - PGPASSWORD=hush
      - PGDATABASE=habitTrack
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run startDev"

  db:
    container_name: dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=habitTrack
      - POSTGRES_USER=mongodontbother
      - POSTGRES_PASSWORD=hush
volumes:
  dbdata:
